name: 新功能提议
description: 请求添加一个功能
title: '[NEW] '
labels: []

body:
  # Input | Requset
  - type: textarea
    id: request
    attributes:
      label: 需求功能
      description: |
        您需求Filebox添加的新功能是什么？
    validations:
      required: true
      
  # Optional | Extra description
  - type: textarea
    id: extra-desc
    attributes:
      label: 如果您能够简略提供使用场景就更好了！
